# Generated by Django 4.0.3 on 2022-04-19 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_Token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Token',
                'verbose_name_plural': 'Users Tokens',
            },
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(db_index=True)),
                ('expire_hour', models.IntegerField(default=7200)),
                ('domain', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Session_User_Token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Token',
                'verbose_name_plural': 'Session Tokens',
            },
        ),
    ]
