# Generated by Django 4.0.3 on 2022-07-20 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=120)),
                ('created_date', models.DateTimeField(db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recovery Token',
                'verbose_name_plural': 'Recovery Tokens',
            },
        ),
    ]
