# Generated by Django 4.0.3 on 2022-07-18 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=250, null=True)),
                ('Priority', models.IntegerField(blank=True, null=True)),
                ('Phone', models.CharField(blank=True, max_length=250, null=True)),
                ('Description', models.CharField(blank=True, max_length=250, null=True)),
                ('Email', models.CharField(blank=True, max_length=250, null=True)),
                ('Url', models.CharField(blank=True, max_length=250, null=True)),
                ('Status', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cantidad',
            new_name='Cantidad',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='marca',
            new_name='Marca',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='precio',
            new_name='Precio',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='serialCode',
            new_name='SerialCode',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='skin_id',
            new_name='Skin',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='Status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='userpost',
        ),
        migrations.AddField(
            model_name='category',
            name='Status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='products.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='User',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Prov',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Provider', to='products.provider'),
            preserve_default=False,
        ),
    ]
