# Generated by Django 4.0.3 on 2022-07-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skin',
            name='user',
        ),
    ]
