# Generated by Django 4.0.3 on 2022-07-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinorder',
            name='order',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
